# Generated by Django 5.1.5 on 2025-03-10 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('fill_level', models.FloatField(default=0.0)),
                ('last_collected', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_id', models.CharField(max_length=100, unique=True)),
                ('credits', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('credits_earned', models.IntegerField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteapp.wastebin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteapp.userprofile')),
            ],
        ),
    ]
