# Generated by Django 5.1.7 on 2025-03-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastedisposalrecord',
            name='name',
        ),
    ]
