# Generated by Django 5.1.7 on 2025-04-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastedisposal',
            old_name='barcode',
            new_name='barcode_id',
        ),
    ]
