# Generated by Django 5.1.7 on 2025-04-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0002_rename_barcode_wastedisposal_barcode_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastedisposal',
            old_name='barcode_id',
            new_name='barcode',
        ),
    ]
