# Generated by Django 5.1.7 on 2025-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0002_wastedisposalrecord_delete_wastedisposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposalrecord',
            name='barcode_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wastedisposalrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
