# Generated by Django 5.1.7 on 2025-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0002_remove_wastedisposalrecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposalrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
