# Generated by Django 5.1.7 on 2025-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0003_wastedisposalrecord_barcode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposalrecord',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
