# Generated by Django 5.1.7 on 2025-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0003_rename_barcode_id_wastedisposal_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
    ]
