# Generated by Django 5.1.7 on 2025-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0003_wastedisposalrecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposalrecord',
            name='ir_sensor',
            field=models.BooleanField(default=False),
        ),
    ]
