# Generated by Django 5.1.7 on 2025-03-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0004_wastedisposalrecord_ir_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastedisposalrecord',
            name='name',
        ),
    ]
