# Generated by Django 5.1.7 on 2025-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0004_userprofile_total_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedisposal',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
