# Generated by Django 5.1.7 on 2025-04-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0005_wastedisposal_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastedisposal',
            name='credits',
        ),
    ]
