# Generated by Django 5.1.7 on 2025-04-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0006_remove_wastedisposal_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeemhistory',
            old_name='credits_redeemed',
            new_name='credits_used',
        ),
    ]
