# Generated by Django 5.1.7 on 2025-04-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0007_rename_credits_redeemed_redeemhistory_credits_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemhistory',
            name='reward',
            field=models.CharField(max_length=255),
        ),
    ]
