# Generated by Django 5.1.7 on 2025-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0008_alter_redeemhistory_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedisposal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
